myapp2/app1/urls.py
from django.urls import path
from .views import detail, info

# 앱의 네임스페이스 지정
app_name = "app1"

urlpatterns = [
    path("", detail, name="detail"),
    path("info/", info, name="info"),
]

myapp2/app2/urls.py
from django.urls import path
from .views import index

app_name = "app2"


urlpatterns = [
    path("", index, name="detail"),
]

myapp2/config/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app1/", include("app1.urls")),
    path("app2/", include("app2.urls")),
    path("users/", include("users.urls")),
    # http://127.0.0.1:8000/
    path("", index, name="index"),
    # 장고가 제공하는 views(User) 확인
    # path("accounts/", include("django.contrib.auth.urls")),
]

myapp2/users/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    # http://127.0.0.1:8000/users/
    path("", views.user_main, name="main"),
    # http://127.0.0.1:8000/users/register/
    path("register/", views.signup, name="register"),
    # http://127.0.0.1:8000/users/login/
    # path("login/", views.common_login, name="login"),
    # http://127.0.0.1:8000/users/logout/
    # path("logout/", views.common_logout, name="logout"),
    # 장고가 제공하는 views 사용하기 - users의 views.py 에 정의한 common_login 사용 안하도 됨
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # path(
    #     "password_change/",
    #     auth_views.PasswordChangeView.as_view(),
    #     name="password_change",
    # ),
    path(
        "password_change/",
        views.CustomPasswordChangeView.as_view(),
        name="password_change",
    ),
]

myapp2/app1/models.py
from django.db import models

# Create your models here.

myapp2/app2/models.py
from django.db import models

# Create your models here.

myapp2/users/models.py
from django.db import models

# Create your models here.

myapp2/users/forms.py
from django import forms

# 장고에서 제공하는 User 생성폼과 모델 가져오기
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    """
    상속관계

    forms.ModelForm
    |
    BaseUserCreationForm : username, password, password2
    |
    UserCreationForm
    |
    UserForm : User 모든 필드 + 상속(username, password, password2 : BaseUserCreationForm 상속받은거)

    UserCreationForm 클래스를 상속받는 Form 정의
    """

    # 부모가 넘겨주는 email 은 필수 입력 요소가 아님
    # 필수 입력 요소로 만들기 위해 재정의
    email = forms.EmailField(label="이메일")
    # 이메일 필수항목입니다 화면에 뜨게됨 - 이메일을 필수항목으로 하기 위해 재정의 하는 것임 : 비밀번호 초기화 시 이메일 전송을 처리하기 위한 준비단계라고 생각하면됨

    class Meta:
        model = User
        # fields = "__all__" + 상속 : 현재 연결된 user 테이블의 모든 필드가 화면에 보여지게 됨 + 상속된 필드까지
        fields = ["username", "email"]  # + 상속(password, password2) / 필요한 필드만 지정한다고

myapp2/app1/views.py
from django.shortcuts import render


def detail(request):
    return render(request, "app1/detail.html")


def info(request):
    return render(request, "app1/info.html")

myapp2/app2/views.py
from django.shortcuts import render


def index(request):
    return render(request, "app2/detail.html")

myapp2/users/views.py
from django.shortcuts import render, redirect
from .forms import UserForm

# 장고에서 제공하는 User 생성폼과 모델 가져오기
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# 로그인 처리
from django.contrib.auth import authenticate, login, logout

# 비밀번호 변경
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy


def index(request):
    return render(request, "index.html")


def user_main(request):
    return render(request, "users/main.html")


# def signup(request):
#     """
#     회원가입 시 UserCreationForm(아이디,비밀번호,비밀번호 확인) 사용 방식
#     """
#     if request.method == "POST":
#         form = UserCreationForm(
#             request.POST
#         )  # 입력한걸 post 로 보내 / UserCreationForm 장고가 제공해주는 폼
#         if form.is_valid():  # 유효성검증
#             form.save()  # 통과하면 db 저장
#             return redirect("users:login")  # 이동할 페이지
#     else:
#         form = UserCreationForm()  # instance= 이 있다면 바인딩된 폼

#     return render(request, "users/register.html", {"form": form})


def signup(request):
    """
    회원가입 시 UserForm 사용 방식
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("users:login")
    else:
        form = UserForm()

    return render(request, "users/register.html", {"form": form})


def common_login(request):
    """
    개발자가 login 직접 구현시 정의하고 사용.
    직접 구현하지 않고 장고가 제공하는 LoginView 사용 가능
    """
    if request.method == "POST":
        # 사용자 입력값 가져오기
        username = request.POST["username"]
        password = request.POST["password"]
        # 사용자가 존재한다면 권한을 가진 user 객체를 리턴해줌 : authenticate() 함수 역할임
        user = authenticate(request, username=username, password=password)

        if user is not None:
            # 세션에 정보가 담기게 됨
            login(request, user)
            return redirect("index")  # 로그인 되면 index로 가라

    return render(request, "users/login.html")


def common_logout(request):
    """
    개발자가 logout 직접 구현시 정의하고 사용.
    직접 구현하지 않고 장고가 제공하는 LogoutView 사용 가능
    """
    logout(request)  # 세션을 해제해줌
    return redirect("index")


"""
장고에서 USER 작업 시
django.contrib.auth.views 안에 정의된 여러 클래스들 사용 가능

login => LoginView
logout => LogoutView
password 변경 => PassswordChangeView
password 초기화 => PasswordResetView
password 초기화를 위한 이메일 전송 => PasswordResetConfirm
"""


class CustomPasswordChangeView(PasswordChangeView):
    """
    PasswordChangeView 에서 정의한
    template_name 은 registration/password_change_form.html 을 찾게 되어있음
    success_url 은 password_change_done 으로 이동함
    """

    template_name = "users/password_change.html"
    success_url = reverse_lazy("users:login")


def common_password_change(request):
    """
    개발자가 직접 비밀번호 변경 구현시 정의하고 사용.
    django 가 제공하는 PasswordChangeView 사용하면 편하게 비밀번호 변경 가능
    """
    if request.method == "POST":
        form = PasswordChangeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("users:login")
        else:
            form = PasswordChangeForm()

        return render(request, "users/password_change.html", {"form": form})

myapp2/templates/app1/detail.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
  <h1>App1 Detail</h1>
  <a href="{% url 'app1:info' %}" class="btn btn-success">이동</a>
  <img src="{% static 'img/bambi.png' %}" alt="">
{% endblock contents %}

myapp2/templates/app1/info.html
{% extends 'base.html' %}
{% block contents %}
  <a href="{% url 'app1:detail' %}" class="btn btn-success">이동</a>
{% endblock contents %}

myapp2/templates/app2/detail.html
{% extends 'base.html' %}
{% block contents %}
  <h1>App2 Detail</h1>
{% endblock contents %}

myapp2/templates/base.html
{% load static %}   
{% comment %} settings.py 의 STATIC_URL = "static/" 을 가져오라는 의미 {% endcomment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        {% block contents %}{% endblock contents %}
    </div>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

myapp2/templates/errors.html
{% if form.errors %}
  <div class="alert alert-danger">
    {% for field in form %}
      {% if field.errors %}
        <strong>{{field.label}}</strong>
        {{field.errors}}
      {% endif %}
    {% endfor %}
  </div>
{% endif %}

myapp2/templates/index.html
{% extends 'base.html' %}
{% block contents %}
  <h1>INDEX -
    {{request.user}}</h1>
    {% comment %} user를 간단하게 확인할 수 있는 코드 {% endcomment %}
  <ul>
    <li>
      <a href="{% url 'app1:detail' %}">app1</a>
    </li>
    <li>
      <a href="{% url 'app2:detail' %}">app2</a>
    </li>
    <li>
      <a href="{% url 'users:main' %}">users</a>
    </li>
  </ul>
{% endblock contents %}

myapp2/templates/users/login.html
{% extends 'base.html' %}
{% block contents %}
  <div class="row my-3">
    <div class="col-4">
      <h3>로그인</h3>
    </div>
    <div class="col-8">
      <span>또는
        <a href="{% url 'users:register' %}">회원가입 하세요</a>
      </span>
    </div>
  </div>
  <form action="" method="post">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="username">사용자ID</label>
      <input type="text" class="form-control" name="username" id="username">
    </div>
    <div class="form-group mb-3">
      <label for="password">비밀번호</label>
      <input type="password" class="form-control" name="password" id="password">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">로그인</button>
    </div>
  </form>
{% endblock contents %}

myapp2/templates/users/main.html
{% extends 'base.html' %}
{% block contents %}
  <h1 class="pt-3">User Main</h1>
  <ul>
    <li>
      {% comment %} 로그인 정보가 있다면 {% endcomment %}
      {% if user.is_authenticated %}  
      <a href="{% url 'users:logout' %}"> 
        {{user.username}} 
        logout</a>
      {% else %}
      <a href="{% url 'users:login' %}">login</a>
      {% endif %}
    </li>
    <li>
      <a href="{% url 'users:register' %}">register</a>
    </li>
    <li>
      <a href="{% url 'users:password_change' %}">비밀번호 변경</a>
    </li>
  </ul>
{% endblock contents %}

myapp2/templates/users/password_change.html
{% extends 'base.html' %}
{% block contents %}
  <div class="row my-3">
    <div class="col-4">
      <h3>비밀번호 변경</h3>
    </div>
    <div class="col-8">
      <span>또는
        <a href="{% url 'users:register' %}">회원가입 하세요</a>
      </span>
    </div>
  </div>
  <form action="" method="post">
    {% include 'errors.html' %}
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="old_password">기존 비밀번호</label>
      <input type="password" class="form-control" name="old_password" id="old_password" value="{{form.old_password.value|default_if_none:''}}">
    </div>
    <div class="form-group mb-3">
      <label for="new_password1">새 비밀번호</label>
      <input type="password" class="form-control" name="new_password1" id="new_password1" value="{{form.new_password1.value|default_if_none:''}}">
    </div>
    <div class="form-group mb-3">
      <label for="new_password2">새 비밀번호(확인)</label>
      <input type="password" class="form-control" name="new_password2" id="new_password2" value="{{form.new_password2.value|default_if_none:''}}">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">비밀번호 변경</button>
    </div>
  </form>
{% endblock contents %}